repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 24.8.0 # Use a version compatible with your project
    hooks:
    -   id: black
        # If you have specific configurations in pyproject.toml, black should pick them up.
        # Specify language_version if needed, e.g., language_version: python3.10

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Use a version compatible with your project
    hooks:
    -   id: isort
        name: isort (python)
        # If you have configurations in pyproject.toml, isort should pick them up.
