name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - 'app/**'
      - 'tests/**'
      - 'cdk.json'
      - '.github/workflows/cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - 'app/**'
      - 'tests/**'
      - 'cdk.json'
      - '.github/workflows/cd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --only main,infra --no-root
          npm install -g aws-cdk
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy with CDK
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          poetry run cdk deploy --all --require-approval never
